/* Generated by lastchange.py, do not edit.*/

#ifndef GPU_CONFIG_GPU_LISTS_VERSION_H_
#define GPU_CONFIG_GPU_LISTS_VERSION_H_

#define GPU_LISTS_VERSION "3587067cafd6f5b1e567380acb485d96e623ef39"

#endif  // GPU_CONFIG_GPU_LISTS_VERSION_H_
